# Generated by Django 6.1.1 on 2026-10-06 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentorg', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collage',
            new_name='College',
        ),
        migrations.RenameField(
            model_name='college',
            old_name='collage_name',
            new_name='college_name',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='collage',
            new_name='college',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='collage',
            new_name='college',
        ),
    ]
